import apiClient from "@/lib/api-client";

export interface FollowUpTask {
  id: string;
  patientId: string;
  patientName?: string;
  doctorId: string;
  title: string;
  notes?: string;
  type: string;
  dueDate: string;
  priority: "HIGH" | "MEDIUM" | "LOW";
  status: "PENDING" | "COMPLETED" | "SNOOZED" | "CANCELLED";
  autoGenerated?: boolean;
  trigger?: string;
  completedAt?: string;
  completedNote?: string;
  snoozedUntil?: string;
  createdAt: string;
}

export const followUpTaskService = {
  async getTasks(filters?: { status?: string; priority?: string; patientId?: string }) {
    const response = await apiClient.get<{ data: FollowUpTask[] }>("/api/followup-tasks", filters);
    return response.data;
  },

  async getTasksByPatient(patientId: string) {
    const response = await apiClient.get<{ data: FollowUpTask[] }>(`/api/followup-tasks/patient/${patientId}`);
    return response.data;
  },

  async createTask(data: Partial<FollowUpTask>) {
    const response = await apiClient.post<{ data: FollowUpTask }>("/api/followup-tasks", data);
    return response.data;
  },

  async completeTask(taskId: string, completedNote?: string) {
    const response = await apiClient.post<{ data: FollowUpTask }>(`/api/followup-tasks/${taskId}/complete`, { completedNote });
    return response.data;
  },

  async snoozeTask(taskId: string, snoozedUntil: string) {
    const response = await apiClient.post<{ data: FollowUpTask }>(`/api/followup-tasks/${taskId}/snooze`, { snoozedUntil });
    return response.data;
  },

  async deleteTask(taskId: string) {
    const response = await apiClient.delete(`/api/followup-tasks/${taskId}`);
    return response.data;
  },

  async getOverdueTasks() {
    const response = await apiClient.get<{ data: FollowUpTask[] }>("/api/followup-tasks/overdue");
    return response.data;
  }
};

export default followUpTaskService;
